name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
	
jobs:
  build:
    runs-on: self-hosted
  
  
	steps:
	- uses: action/checkout@v2
	- name: Use Node.js ${{ matrix.node-version }}
	  uses: action/setup-node@v1
	  with:
	    node-version: ${{ matrix.node-version }}
	- run: |
    cd client
		npm install
		cd ..
    cd server
		npm install
		